name: XAuth
main: Luthfi\XAuth\Main
version: 0.0.2
api: 5.0.0
author: Luthfi
description: A simple auth plugin for PocketMine-MP
website: https://github.com/LuthMC/XAuth

commands:
  login:
    description: Login to your account.
    usage: "/login <password>"
    permission: "xauth.login"
  register:
    description: Register your account.
    usage: "/register <password> <confirmpassword>"
    permission: "xauth.register"
  resetpassword:
    description: Reset your password.
    usage: "/resetpassword <oldpassword> <newpassword>"
    permission: "xauth.resetpassword"
  profile:
    description: Open your profile settings.
    permission: "xauth.profile"
    
permissions:
  xauth.login:
    description: Allow players to login.
    default: true
  xauth.register::
    description: Allow players to register.
    default: true
  xauth.resetpassword:
    description: Allow players to reset their password.
    deafult: true
  xauth.profile:
    description: Allow players to setting their profile.
    default: true
