#  XAuth Configuration

# If enabled, the player will be auto-logged in based on their IP address from the last session.
auto-login: true

# Enable or disable the title messages
enable_titles: true

# Available language: "en", "id"
language: "en"

# DON'T CHANGE THIS!
config-version: 1.0
